export const API_BASE = import.meta.env.VITE_API_URL || '/api/v1';

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  PARTICIPANT: 'PARTICIPANT',
} as const;

export const REGISTRATION_STATUS = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
} as const;

export const SUBMISSION_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  LOCKED: 'LOCKED',
} as const;

export const TEAM_STATUS = {
  ACTIVE: 'ACTIVE',
  DISQUALIFIED: 'DISQUALIFIED',
  LOCKED: 'LOCKED',
} as const;

export const HACKATHON_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  ARCHIVED: 'ARCHIVED',
} as const;
